### ISSUE TITLE
todo search page

### ISSUE THREAD

**Issue by jcmtallon** [trueStoryJapan/todoNext#69]
- [x] Displays dates for active, displays status for complete or pending. 
- [x] Displays urgency for active, displays info (with urgency, date, etc) for complete/pending.
- [x] Displays progress bar for active, no progress bar for complete/pending. 
- [x] Menu: remove, restart / reactivate for complete/pending.
- [x] Menu: progress, pending, remove, edit, complete for active todos. 
- [ ]
